apiVersion: v1
kind: Pod
metadata:
  name: pod-blue
  labels:
    namesapce: production
    app: web
spec:
  containers:
  - name: pod-blue
    image: kodekloud/webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: blue
