apiVersion: v1
kind: Pod
metadata:
  name: pod-red
  labels:
    namespace: production
    app: web
spec:
  containers:
  - name: pod-red
    image: kodekloud/webapp-color
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red
